### ISSUE TITLE
Memory Allocation Error

### ISSUE THREAD

**Issue by ngarneau** [ngarneau/vecmap#20]
Got this error when running with new languages. The error was on Persian (fa):

```
Traceback (most recent call last):                                                      
  File "/home/ngarneau/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                                                      
    "__main__", mod_spec)                                                               
  File "/home/ngarneau/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)                                                             
  File "/home/ngarneau/workspace/vecmap/src/scripts/experiment.py", line 552, in <module>                                                                                       
    main()                                                                              
  File "/home/ngarneau/workspace/vecmap/src/scripts/experiment.py", line 539, in main
    run_experiment(configs)                                                             
  File "/home/ngarneau/workspace/vecmap/src/scripts/experiment.py", line 214, in run_experiment                                                                                 
    wx1 = whitening_transformation(xw[src_indices])                                     
  File "/home/ngarneau/workspace/vecmap/src/scripts/experiment.py", line 210, in whitening_transformation                                                                       
    u, s, vt = xp.linalg.svd(m, full_matrices=False)             
  File "/home/ngarneau/workspace/vecmap/venv/lib/python3.6/site-packages/cupy/linalg/decomposition.py", line 258, in svd                                                        
    workspace = cupy.empty(buffersize, dtype=a_dtype)            
  File "/home/ngarneau/workspace/vecmap/venv/lib/python3.6/site-packages/cupy/creation/basic.py", line 22, in empty                                                             
    return cupy.ndarray(shape, dtype, order=order)               
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 518, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1106, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 934, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc                                                                                      
  File "cupy/cuda/memory.pyx", line 949, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc                                                                                     
  File "cupy/cuda/memory.pyx", line 697, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 6490425856 bytes (total 15271853056 bytes)
```

**Comment by ngarneau** [comment]
It would be nice to know exactly the maximum amount of memory needed given the size of the embedding matrix.
